--------------------------------------------------------
--  File created - Tuesday-December-26-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMISSION_QUESTIONS
--------------------------------------------------------

  CREATE TABLE "ACADEMIA_PLUS_NEW"."ADMISSION_QUESTIONS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"QUESTION" VARCHAR2(255 BYTE), 
	"OPTION_A" VARCHAR2(255 BYTE), 
	"OPTION_B" VARCHAR2(255 BYTE), 
	"OPTION_C" VARCHAR2(255 BYTE), 
	"OPTION_D" VARCHAR2(255 BYTE), 
	"ANSWER" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS
SET DEFINE OFF;
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (1,'Her thinking leans ____ democracy.','with','towards','for','None of these','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (2,'He got too tired _____ over work.','because of','because off','on','for','A');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (3,'_____ his principles, he has to be very careful.','with regard of','with regard on','with regard to','None of these','C');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (4,'Building has been built _____ the new plan.','accordance to','in accordance with','for','about','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (5,'He crossed the broken bridge ____ warning.','in spite of','in spite off','on','about','A');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (6,'He was seen _____ to the school.','went','going','gone','go','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (7,'She ____ in the sun for 1 hour.','sitting','has been sitting','has been sit','has sit','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (8,'____ it help you in your studies ?','will','was','is','are','A');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (9,'I ____ never seen such a picture before.','did','was','have','has','C');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (10,'Words of the same sound is ?','Soundnyms','Antonyms','Homonyms','None of these','C');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (11,'Sounding the same but spelled differently ?','Symphonious','Homophonous','Synonyms','Saminymous','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (12,'Choose the correct answer ?','My friend has got a new job.','My friend has got a new work.','My friend is got a new job.','My friend did got a new job.','A');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (13,'Choose the correct sentence.','Do you like a glass of water ?','Would you like a glass of water ?','Would you like the glass of water ?','Do you like the glass of water ?','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (14,'Antonym of Ad-lib ?','Improvise','Extemporized','Deliberate','Spontaneous','C');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (15,'Antonym of Imperil ?','Safeguard','Endanger','Hazard','Jeopardise','A');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (16,'Antonym of Inscrutable ?','Baffling','Obvious','Confuse','Reduce','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (17,'Antonym of Licentious ?','Continent','Confused talk','Clear','Close','A');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (18,'Antonym of Rabid ?','Frantic','Sober','Chaos','Vulgar','B');
Insert into ACADEMIA_PLUS_NEW.ADMISSION_QUESTIONS (ID,QUESTION,OPTION_A,OPTION_B,OPTION_C,OPTION_D,ANSWER) values (19,'Antonym of Ravenous ?','Greedy','Very Hungry','Assuaged','None of these','C');
--------------------------------------------------------
--  Constraints for Table ADMISSION_QUESTIONS
--------------------------------------------------------

  ALTER TABLE "ACADEMIA_PLUS_NEW"."ADMISSION_QUESTIONS" MODIFY ("ID" NOT NULL ENABLE);