--------------------------------------------------------
--  File created - Friday-February-09-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASSIGNMENTS
--------------------------------------------------------

  CREATE TABLE "ACADEMIA_PLUS_NEW"."ASSIGNMENTS" 
   (	"COURSE_TITLE" VARCHAR2(512 BYTE), 
	"ASSIGNMENT_TITLE" VARCHAR2(512 BYTE), 
	"INSTRUCTIONS" VARCHAR2(512 BYTE), 
	"SUB_DATE" DATE, 
	"CLASS" VARCHAR2(50 BYTE),
  "ASSIGNMENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE,
  "TEACHER_ID" VARCHAR2(50 BYTE)
   ) 