--------------------------------------------------------
--  File created - Monday-February-26-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURSEOVERVIEW
--------------------------------------------------------

  CREATE TABLE "ACADEMIA_PLUS_NEW"."COURSEOVERVIEW" 
   (	"CLASS" VARCHAR2(512 BYTE), 
	"OVERVIEW" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  NO INMEMORY ("OVERVIEW") ;
REM INSERTING into ACADEMIA_PLUS_NEW.COURSEOVERVIEW
SET DEFINE OFF;
Insert into ACADEMIA_PLUS_NEW.COURSEOVERVIEW (CLASS,OVERVIEW) values ('Three','Class 3: Level Up Your Learning Adventure! Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences! Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects: Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world. English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination. Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science. Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.Class 2: Level Up Your Learning Adventure! Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences! Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects: Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world. English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination. Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science. Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.');
Insert into ACADEMIA_PLUS_NEW.COURSEOVERVIEW (CLASS,OVERVIEW) values ('Four','Class 4: Level Up Your Learning Adventure! Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences! Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects: Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world. English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination. Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science. Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.Class 2: Level Up Your Learning Adventure! Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences! Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects: Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world. English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination. Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science. Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.');
Insert into ACADEMIA_PLUS_NEW.COURSEOVERVIEW (CLASS,OVERVIEW) values ('Five','Class 5: Level Up Your Learning Adventure! Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences! Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects: Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world. English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination. Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science. Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.Class 2: Level Up Your Learning Adventure! Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences! Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects: Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world. English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination. Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science. Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.');
Insert into ACADEMIA_PLUS_NEW.COURSEOVERVIEW (CLASS,OVERVIEW) values ('One','Class 1 is an exciting start to the educational journey. Students will be introduced to fundamental subjects
          like Mathematics, English, Science, and more. The curriculum focuses on building a strong foundation for future learning.
          Topics covered include basic arithmetic, language development, and an introduction to the world of science. 
          Students will engage in interactive learning activities to make the learning process fun and engaging.
          

          Join us on this educational adventure in Class 1!');
Insert into ACADEMIA_PLUS_NEW.COURSEOVERVIEW (CLASS,OVERVIEW) values ('Two','Class 2: Level Up Your Learning Adventure!
Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences!

Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects:

Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world.

English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination.

Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science.

Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.Class 2: Level Up Your Learning Adventure!
Ready to soar to new heights in your educational journey? Class 2 welcomes you with open arms, packed with exciting challenges and enriching experiences!

Building on the strong foundation laid in Class 1, you''ll embark on a deeper dive into key subjects:

Mathematics: Master addition, subtraction, multiplication, and division, tackling more complex problems with confidence. Explore shapes, patterns, and measurements, unlocking the secrets of the mathematical world.

English: Expand your vocabulary with new and exciting words. Craft captivating stories, write informative reports, and master the art of clear communication. Dive into the magical world of literature, encountering beloved characters and enriching your imagination.

Science: Unleash your inner scientist! Investigate the wonders of the natural world, conducting experiments, making observations, and forming your own conclusions. Explore topics like plants, animals, weather, and the human body, igniting a lifelong love for science.

Beyond the Core: Don''t forget the fun! Class 2 introduces you to other engaging subjects like social studies, art, music, and physical education. Discover different cultures, express your creativity, explore the power of music, and stay active, fostering a well-rounded development.');
