CREATE TABLE ACADEMIA_PLUS_NEW.NOTICES (
    NOTICE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOTICE_FILE VARCHAR2(255),
    NOTICE_TITLE VARCHAR2(255),
    PUBLICATION_DATE DATE DEFAULT SYSDATE
);
