CREATE TABLE "ACADEMIA_PLUS_NEW"."RESOURCES" 
   (  "RESOURCE_ID" VARCHAR2(20 BYTE), 
  "RESOURCE_NAME" VARCHAR2(512 BYTE), 
  "TYPE" VARCHAR2(512 BYTE), 
  "AUTHOR" VARCHAR2(512 BYTE), 
  "RESOURCE_FILE" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ACADEMIA_PLUS_NEW.RESOURCES
SET DEFINE OFF;
Insert into ACADEMIA_PLUS_NEW.RESOURCES (RESOURCE_ID,RESOURCE_NAME,TYPE,AUTHOR,RESOURCE_FILE) values ('1','???? ????? ??','????? ??????','NCTV','1707242106140-Primary - 2019 - (B.Version.) - Class-1 Bangla OPT.pdf');
Insert into ACADEMIA_PLUS_NEW.RESOURCES (RESOURCE_ID,RESOURCE_NAME,TYPE,AUTHOR,RESOURCE_FILE) values ('2','English for Today','English','NCTV','1707290131925-Primary - 2019 - (B.Version.) - Class-1 English For Today OPT.pdf');
--------------------------------------------------------
--  DDL for Index SYS_C008231
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACADEMIA_PLUS_NEW"."SYS_C008231" ON "ACADEMIA_PLUS_NEW"."RESOURCES" ("RESOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger RESOURCES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ACADEMIA_PLUS_NEW"."RESOURCES_TRIGGER" 
BEFORE INSERT ON "ACADEMIA_PLUS_NEW"."RESOURCES"
FOR EACH ROW
BEGIN
   SELECT "RESOURCES_ID_SEQ".NEXTVAL INTO :NEW."RESOURCE_ID" FROM DUAL;
END;

/
ALTER TRIGGER "ACADEMIA_PLUS_NEW"."RESOURCES_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "ACADEMIA_PLUS_NEW"."RESOURCES" ADD PRIMARY KEY ("RESOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;