--------------------------------------------------------
--  File created - Saturday-February-24-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUB_ASSIGNMENTS
--------------------------------------------------------

  CREATE TABLE "ACADEMIA_PLUS_NEW"."SUB_ASSIGNMENTS" 
   (	"ID" VARCHAR2(512 BYTE), 
	"UPLOADED_FILE" VARCHAR2(512 BYTE), 
	"TURNIN" VARCHAR2(20 BYTE), 
	"CLASS" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ACADEMIA_PLUS_NEW.SUB_ASSIGNMENTS
SET DEFINE OFF;
Insert into ACADEMIA_PLUS_NEW.SUB_ASSIGNMENTS (ID,UPLOADED_FILE,TURNIN,CLASS,ASSIGNMENT_ID) values ('000004','1708699535791-JU NCPC 2023 - Online Preliminary Contest Editorial.pdf','1','Two','02001');
Insert into ACADEMIA_PLUS_NEW.SUB_ASSIGNMENTS (ID,UPLOADED_FILE,TURNIN,CLASS,ASSIGNMENT_ID) values ('000004','1708699582424-Capture2.PNG','1','Two','02002');
